name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_NAME }}/providers/${{ secrets.GCP_PROVIDER_NAME }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      # Install Firebase CLI (if not already installed)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate Firebase using the access token from Google Cloud
      - name: Authenticate Firebase
        run: firebase login:ci --token "$(gcloud auth print-access-token)"

      # Run Firebase deployment
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
