name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_NAME }}/providers/${{ secrets.GCP_PROVIDER_NAME }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      # Install dependencies for Firebase (if needed)
      - name: Install Python dependencies
        run: pip install firebase-admin

      # Run the Firebase script
      - name: Run Firebase Script
        run: python FirebaseScript.py
